# Generated by Django 5.0.14 on 2026-09-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="e.g. 'posting.submitted', 'decision.approve'", max_length=100
                    ),
                ),
                (
                    "object_type",
                    models.CharField(help_text="e.g. 'postings.JobPosting'", max_length=100),
                ),
                ("object_id", models.CharField(max_length=64)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system-initiated events (e.g. the moderation pipeline itself).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"], name="audit_audit_object__0e78a5_idx"
                    ),
                    models.Index(fields=["action"], name="audit_audit_action_203f66_idx"),
                ],
            },
        ),
    ]
