# Generated by Django 5.0.14 on 2026-09-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("postings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("posting_version", models.PositiveIntegerField()),
                ("policy_version", models.PositiveIntegerField(blank=True, null=True)),
                ("model_version", models.CharField(blank=True, max_length=64)),
                ("engine_version", models.CharField(blank=True, max_length=64)),
                ("risk_score", models.FloatField(blank=True, null=True)),
                (
                    "routing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AUTO_APPROVE", "Auto-approve"),
                            ("AUTO_REJECT", "Auto-reject"),
                            ("HUMAN_REVIEW", "Human review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_runs",
                        to="postings.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ADVANCE_FEE", "Advance Fee"),
                            ("PII_HARVEST", "Pii Harvest"),
                            ("ILLEGAL_WORK", "Illegal Work"),
                            ("MLM_RECRUITMENT", "Mlm Recruitment"),
                            ("OFF_PLATFORM_REDIRECT", "Off Platform Redirect"),
                            ("DISCRIMINATORY", "Discriminatory"),
                            ("MISLEADING_COMP", "Misleading Comp"),
                            ("NO_COMP_DISCLOSURE", "No Comp Disclosure"),
                            ("SPAM_DUPLICATE", "Spam Duplicate"),
                            ("GHOST_JOB", "Ghost Job"),
                            ("KEYWORD_STUFFING", "Keyword Stuffing"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("RULE", "Rule"), ("MODEL", "Model"), ("DEDUPE", "Dedupe")],
                        max_length=16,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("rule_id", models.CharField(blank=True, max_length=64)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("reason", models.TextField(blank=True)),
                ("contributing_terms", models.JSONField(blank=True, default=list)),
                ("is_false_positive", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="moderation.moderationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-confidence"],
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("REQUEST_CHANGES", "Request changes"),
                            ("ESCALATE", "Escalate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="moderation.moderationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_claims",
                        to="postings.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ["-claimed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="moderationrun",
            index=models.Index(
                fields=["posting", "posting_version"], name="moderation__posting_f50af4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(fields=["run", "category"], name="moderation__run_id_7773b1_idx"),
        ),
        migrations.AddIndex(
            model_name="reviewclaim",
            index=models.Index(
                fields=["posting", "expires_at"], name="moderation__posting_17e5dd_idx"
            ),
        ),
    ]
